version: '3.5'
services:
  webapp:
    image: ${registry}:${git_commit_id}
    hostname: nginxApp
    expose:
      - "5000"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx
    depends_on:
      - webapp
    ports:
      - "8070:80"
networks:
  default:
    driver: bridge
    name: webapp