version: '3.5'
services:
  webapp:
    image: ${registry}:${git_commit_id}
    hostname: nginxApp
    volumes:
      - ./nginx.conf:/etc/nginx:ro
    expose:
      - "80"
  nginx:
    image: nginx:latest
    depends_on:
      - webapp
    ports:
      - "80:80"
networks:
  default:
    driver: bridge
    name: webapp